### ISSUE TITLE
Tooltips append whitespace

### ISSUE THREAD

**Issue by Venrix** [taskforcehellcat/wiki#44]
When the Tooltip component is used, a whitespace character is appended:

![2023-02-06 13 58 36](https://user-images.githubusercontent.com/35926556/216978163-ef2f43a1-633e-41ba-b76d-2f809df9c01a.png)

span tags don't seem to have this issue, so it must have something to do with the custom component.

**Comment by pantoffelemmy** [comment]
fixed as of 3a67d1b45714912b659fb5f9210927d326558467

**Comment by pantoffelemmy** [comment]
> ~fixed as of [3a67d1b](https://github.com/taskforcehellcat/wiki/commit/3a67d1b45714912b659fb5f9210927d326558467)~

Well that turned out to be false.
The changes I made in that commit remove the whitespaces on my local dev server but they seem to persist deployed. Is it possible that Netlify doesn't recompile the source because there are only whitespace changes? I only removed two newlines after all.

**Comment by pantoffelemmy** [comment]
It is correct following this [deploy preview](https://deploy-preview-33--tfhcwiki.netlify.app/articles/ausbildung/fahrzeugerkennung). I'm confused.

**Comment by Venrix** [comment]
just cleared cache & redeployed on netlify. check if it's fixed now

**Comment by Venrix** [comment]
fixed as of 3a67d1b45714912b659fb5f9210927d326558467

netlify branch deploys were just butchered after repo transfer
