### ISSUE TITLE
Tooltips overlap with tooltip-texts

### ISSUE THREAD

**Issue by LeonTReal** [taskforcehellcat/wiki#45]
Title says it all. Issue can be found [here](https://markdown.wiki.taskforcehellcat.de/articles/ausbildung/fahrzeugerkennung#sch%C3%BCtzenpanzer).
![grafik](https://user-images.githubusercontent.com/82829513/218755802-883889a0-6db7-43c2-b953-0720befa41e9.png)

**Comment by pantoffelemmy** [comment]
I added a z-Index of 99 to the tooltip css class. I think it was just a little oversight that none was set.
@Venrix if that was intentional feel free to reopen.
