### ISSUE TITLE
Navigation bar not updating correctly

### ISSUE THREAD

**Issue by LeonTReal** [taskforcehellcat/wiki#52]
Steps to reproduce:
1. Visit any wiki page containing example boxes (Befehlsausgabe, Fahren im Konvoi, Blutkreislauf, for example)
2. Navigate to any other wiki page
3. Mind the navigation bar

All elements of the previous page will be kept on the new wiki page.

This only happens when navigating from pages containing example boxes, therefore I assume that they cause this issue.

**Comment by pantoffelemmy** [comment]
The problem disappears if you remove the `transition:slide` directive of the ExampleBox component.

**Comment by pantoffelemmy** [comment]
fixed as of c09b5539cafcfac0b95d7b661a350fc79202fdd3. The transition:slide directive didn't work anyway so it's no loss.
I like the idea of having animations with the example boxes though, we should keep that in mind.
