### ISSUE TITLE
Browser tab name not changing correctly

### ISSUE THREAD

**Issue by LeonTReal** [taskforcehellcat/wiki#59]
Steps to reproduce:

1. Go to wiki homepage
2. Navigate to any wiki page
3. Navigate to any other wiki page via the sidebar menu

Mind the browser tab name. The tab name of the first visited wiki page will be kept and not changed when navigating through different wiki pages.

![photo_2023-03-08_13-10-04](https://user-images.githubusercontent.com/82829513/223710838-a11d3fd1-739d-4859-9e2a-28b86f56d0df.jpg)
![photo_2023-03-08_13-10-34](https://user-images.githubusercontent.com/82829513/223710880-c754ceff-d860-4d87-a933-45654d8a10ba.jpg)
![photo_2023-03-08_13-10-46](https://user-images.githubusercontent.com/82829513/223710898-f72853c1-c10e-4039-bba5-979a16763eaf.jpg)
![photo_2023-03-08_13-10-57](https://user-images.githubusercontent.com/82829513/223710918-ec180ced-5b9d-41a8-9d58-8f37e96dac40.jpg)

**Comment by pantoffelemmy** [comment]
Thanks, I think I introduced this bug with the recent merging of the opengraph feature branch. I'll look into it.
