### ISSUE TITLE
Add "technical" pages to the wiki

### ISSUE THREAD

**Issue by LeonTReal** [taskforcehellcat/wiki#78]
Said pages should contain:

- [x] Setting up the modpack
- [x] Setting up TS3 with ACRE2 Plugin
- [x] Correctly joining the TS3 and A3 Servers
- [ ] Some kind of "troubleshooting" or "FAQ" page?

**Comment by pantoffelemmy** [comment]
Do we want to keep this issue around until we decided on the FAQ section?

**Comment by pantoffelemmy** [comment]
> Do we want to keep this issue around until we decided on the FAQ section?

Feel free to reopen if yes.
